In [1]:
import pickle   # importing pickle for saving and loading machine learning models
import pandas as pd  # importing pandas for analyzing, cleaning, exploring, and manipulating data
from sklearn.model_selection import train_test_split  # importing train_test_split for spliting the data
from imblearn.over_sampling import SMOTE  # importing SMOTE for Balancing the Data

In [2]:
df=pd.read_csv(r"C:\Users\de\Downloads\loan_approved (1).csv")

In [3]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [4]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area',
       'Loan_Status (Approved)'],
      dtype='object')

In [5]:
df.isnull().sum()

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [6]:
df.loc[df['Gender'].isnull(),'Gender']="Male"  # Filling null value using Most_Frequent Elements of Gender column.

In [7]:
df.loc[df['Married'].isnull(),'Married']="Yes"

In [8]:
df.loc[df['Dependents'].isnull(),'Dependents']='0'

In [9]:
df.loc[df['Self_Employed'].isnull(),'Self_Employed']='No'

In [10]:
#  Filling null values using Median of LoanAmount
df.loc[df['LoanAmount'].isnull(),'LoanAmount']=df['LoanAmount'].median()

In [11]:
#  Filling null values using Most_Frequent value of Loan_Amount_Term column
df.loc[df['Loan_Amount_Term'].isnull(),'Loan_Amount_Term']=360.0

In [12]:
df.loc[df['Credit_History'].isnull(),'Credit_History']=0.0    # Filling null values of Credit_History

In [13]:
df.isnull().sum()

Loan_ID                   0
Gender                    0
Married                   0
Dependents                0
Education                 0
Self_Employed             0
ApplicantIncome           0
CoapplicantIncome         0
LoanAmount                0
Loan_Amount_Term          0
Credit_History            0
Property_Area             0
Loan_Status (Approved)    0
dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

class ModifiedLabelEncoder(LabelEncoder):
    def fit_transform(self, y, *args, **kwargs):
        return super().fit_transform(y).reshape(-1, 1)

    def transform(self, y, *args, **kwargs):
        return super().transform(y).reshape(-1, 1)

In [15]:
def divide_by_12(x):
    return x / 12

def same(x):
    return x

In [28]:
# Load a preprocessor object from a pickled file
from sklearn import preprocessing
with open(r"C:\Users\de\svmpreprocesspickle.pkl","rb")as f:
    preprocessor=pickle.load(f)

In [29]:
preprocessor

ColumnTransformer(transformers=[('OHE columns', OneHotEncoder(),
                                 ['Self_Employed', 'Property_Area', 'Gender']),
                                ('Label_encoder', ModifiedLabelEncoder(),
                                 'Married'),
                                ('standard_scaler', StandardScaler(),
                                 ['ApplicantIncome', 'CoapplicantIncome',
                                  'LoanAmount']),
                                ('custom',
                                 FunctionTransformer(func=<function divide_by_12 at 0x000002BA67FA07C0>),
                                 ['Loan_Amount_Term']),
                                ('pass through',
                                 FunctionTransformer(func=<function same at 0x000002BA67FA0AE0>),
                                 ['Credit_History']),
                                ('ordinal dependents',
                                 OrdinalEncoder(categories=[['0', '1', '2',
                                                             '3+']]),
                                 ['Dependents']),
                                ('ordinal education',
                                 OrdinalEncoder(categories=[['Not Graduate',
                                                             'Graduate']]),
                                 ['Education']),
                                ('Label Label encoder', ModifiedLabelEncoder(),
                                 ['Loan_Status (Approved)'])])

In [30]:
# Spliting the data into train and test
train,test,_,_=train_test_split(df,df['LoanAmount'],test_size=0.2)

In [31]:
train['Loan_Status (Approved)'].value_counts()

Loan_Status (Approved)
Y    336
N    155
Name: count, dtype: int64

In [32]:
train

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
356,LP002149,Male,Yes,2,Graduate,No,8333,3167.000000,165.0,360.0,1.0,Rural,Y
117,LP001405,Male,Yes,1,Graduate,No,2214,1398.000000,85.0,360.0,0.0,Urban,Y
586,LP002916,Male,Yes,0,Graduate,No,2297,1522.000000,104.0,360.0,1.0,Urban,Y
568,LP002840,Female,No,0,Graduate,No,2378,0.000000,9.0,360.0,1.0,Urban,N
383,LP002234,Male,No,0,Graduate,Yes,7167,0.000000,128.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,LP002720,Male,Yes,3+,Graduate,No,4281,0.000000,100.0,360.0,1.0,Urban,Y
314,LP002024,Male,Yes,0,Graduate,No,2473,1843.000000,159.0,360.0,1.0,Rural,N
335,LP002106,Male,Yes,0,Graduate,Yes,5503,4490.000000,70.0,360.0,1.0,Semiurban,Y
389,LP002250,Male,Yes,0,Graduate,No,5488,0.000000,125.0,360.0,1.0,Rural,Y
428,LP002369,Male,Yes,0,Graduate,No,2920,16.120001,87.0,360.0,1.0,Rural,Y

In [33]:
# Transform the training data using the preprocessor object or PipeLine
processed_data=preprocessor.fit_transform(train)

C:\Users\de\AppData\Local\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [34]:
processed_data

array([[1., 0., 1., ..., 2., 1., 1.],
       [1., 0., 0., ..., 1., 1., 1.],
       [1., 0., 0., ..., 0., 1., 1.],
       ...,
       [0., 1., 0., ..., 0., 1., 1.],
       [1., 0., 1., ..., 0., 1., 1.],
       [1., 0., 1., ..., 0., 1., 1.]], shape=(491, 16))

In [35]:
# Extract the features (all columns except the last one) from the processed data
x_train=processed_data[:,:-1]

In [36]:
# Extract the target variable (last column) from the processed data
y_train=processed_data[:,-1] # Last column is target

In [37]:
y_train

array([1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
       1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1.,
       0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1.,
       1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.])

In [38]:
# Initialize the SMOTE (Synthetic Minority Over-sampling Technique) object into variable
smote=SMOTE()

In [39]:
# Apply SMOTE to the training data to balance the class distribution
x_train_smote,y_train_smote=smote.fit_resample(x_train,y_train)

In [40]:
len(y_train)  # Checking length of actual y_train

491

In [41]:
len(y_train_smote)

672

In [42]:
from sklearn.svm import SVC  # # assign Support vector classifier
svclassifier = SVC() ## base model with default parameters
svclassifier.fit(x_train_smote,y_train_smote)  ## Fit the SVC to the resampled training data

SVC()

In [43]:
test_processed=preprocessor.transform(test)  # Transform the test data using the preprocessor

C:\Users\de\AppData\Local\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [44]:
x_test=test_processed[:,:-1]  # Extract the features (all columns except the last one) from the processed data
y_test=test_processed[:,-1]   # Extract the target variable (last column) from the processed data

In [45]:
y_test

array([1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 0., 0., 1.])

In [46]:
# Getting predictions from model
y_pred=svclassifier.predict(x_test)

In [47]:
# Importing the classification_report function from sklearn.metrics
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
# Printing the classification report comparing the true labels (y_test) and the predicted labels (y_pred)
print(confusion_matrix(y_test,y_pred))

[[ 4 33]
 [ 6 80]]

In [48]:
print(accuracy_score(y_test,y_pred))

0.6829268292682927

In [49]:
from itertools import product  # Importing the product function from itertools module

param_grid_linear = {           #  Define Parameter grid for linear kernel SVM
    'C': [0.1, 5, 10,50,60,70],
    'kernel': ['linear'],
    'gamma': ['scale', 'auto']
}
param_grid_rbf = {              # Define Parameter grid for Radial Basic Function-RBF
    'C': [0.1, 5, 10,50,60,70],
    'kernel': ['rbf'],
    'gamma': ['scale', 'auto']
}
param_grid_poly = {             # Define Parameters grid for Polynomial kernel
    'C': [0.1, 5, 10,50,60,70],
    'kernel': ['poly'],
    'gamma': ['scale', 'auto'],
    'degree': [2, 3, 4]
}

In [50]:
param_grid1=[param_grid_linear,param_grid_rbf,param_grid_poly]

In [51]:
from sklearn.model_selection import RandomizedSearchCV

# Assigning SVC model into variables
model=SVC()
grid = RandomizedSearchCV(model,param_distributions=param_grid1, refit = True, verbose = 1,scoring='f1',cv=3)

# fitting the model for grid search
grid.fit(x_train_smote,y_train_smote)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=3, estimator=SVC(),
                   param_distributions=[{'C': [0.1, 5, 10, 50, 60, 70],
                                         'gamma': ['scale', 'auto'],
                                         'kernel': ['linear']},
                                        {'C': [0.1, 5, 10, 50, 60, 70],
                                         'gamma': ['scale', 'auto'],
                                         'kernel': ['rbf']},
                                        {'C': [0.1, 5, 10, 50, 60, 70],
                                         'degree': [2, 3, 4],
                                         'gamma': ['scale', 'auto'],
                                         'kernel': ['poly']}],
                   scoring='f1', verbose=1)

In [52]:
svclassifier = SVC(C=70, gamma='auto',kernel='linear' ) ## base model with default parameters
svclassifier.fit(x_train_smote,y_train_smote)

SVC(C=70, gamma='auto', kernel='linear')

In [53]:
y_hat=svclassifier.predict(x_test)

In [54]:
accuracy_score(y_test,y_hat)

0.7804878048780488

In [55]:
print(x_train_smote)

[[1.         0.         1.         ... 1.         2.         1.        ]
 [1.         0.         0.         ... 0.         1.         1.        ]
 [1.         0.         0.         ... 1.         0.         1.        ]
 ...
 [1.         0.         1.         ... 0.20344907 2.         1.        ]
 [1.         0.         0.         ... 0.59087997 1.81824005 0.        ]
 [0.36491888 0.63508112 0.         ... 0.         0.         1.        ]]

In [56]:
print(classification_report(y_test,y_hat))

              precision    recall  f1-score   support

         0.0       0.67      0.54      0.60        37
         1.0       0.82      0.88      0.85        86

    accuracy                           0.78       123
   macro avg       0.74      0.71      0.72       123
weighted avg       0.77      0.78      0.77       123

In [62]:
svclassifier.predict([[1.3,1.1,0.05,0.34,0.67,0.45,0.23,0.89,0.06,0.33,0.99,0.17,0.66,0.28,0.11]])

array([1.])

In [64]:
with open("svmpreprocesspickle.pkl", "wb") as f:
          pickle.dump(svclassifier,f)